### ISSUE TITLE
Logo Proporsal for Laravel-Coinbase

### ISSUE THREAD

**Issue by LuigiBaute** [shakurov/laravel-coinbase#1]
Greetings @shakurov  ,

I was passing by (this repository) and tought I'd like to collaborate by proposing a logo
if that's something that may interest you! let me know!

I'm a Graphic Designer and an Open Source enthusiastic
looking to improve my portfolio and collaborate to really cool projects like this one!

Best Regards,
-Luigi.

**Comment by shakurov** [comment]
Hey @LuigiBaute,

Thanks for your interest in our project.

I don't think that we need logo for this project right now, but if something changes in the future I'll let you know.

**Comment by LuigiBaute** [comment]
Ok thanks, @shakurov .

That's perfect, if you ever need a Graphic Designer, let me know.
