### ISSUE TITLE
Laravel 8.x compatibility

### ISSUE THREAD

**Issue by antimech** [shakurov/laravel-coinbase#11]
Our library needs to be keep up to date with industry. Here is some things we need to do:
- [x] Opt for PHP `^7.3|^8.0` composer dependency
- [x] Opt for **PHPUnit** `^9.3.3` composer dependency
- [x] Opt for **Testbench** `^6.0.0` composer dependency
- [x] Opt for **Guzzle** `^7.0.1` composer dependency
- [x] Remove `Laravel 5` from tags in `composer.json` as it's gonna be compatible with newer versions

Each dependency requires to follow it's upgrade guide to avoid breaking changes. All tests must pass.

PRs are welcome!

**Comment by AlaaElrifaie** [comment]
Please merge this PR https://github.com/shakurov/laravel-coinbase/pull/13
So that we can use the library via composer on Laravel 8.

**Comment by antimech** [comment]
@AlaaElrifaie thank you for your interest! Merged.

The release will soon be updated on Packagist. Until then you can use this:
```json
"repositories": [
    {
        "type": "git",
        "url": "https://github.com/shakurov/laravel-coinbase.git"
    }
],
"require":{
    "shakurov/laravel-coinbase": "^0.7.7"
}
```
