### ISSUE TITLE
How to execute queued Jobs

### ISSUE THREAD

**Issue by spartyboy** [shakurov/laravel-coinbase#12]
How do I execute queued jobs for this package because i can't find any documentation on an artisan command to handle that

**Comment by spartyboy** [comment]
or they are dispatched to the laravel queue?

**Comment by antimech** [comment]
> How do I execute queued jobs for this package because i can't find any documentation on an artisan command to handle that
```shell
php artisan queue:work
```

> or they are dispatched to the laravel queue?

Yes it is. Please refer to the [Laravel queues docs](https://laravel.com/docs/10.x/queues).
