### ISSUE TITLE
Class coinbase does not exist

### ISSUE THREAD

**Issue by vdomah** [shakurov/laravel-coinbase#2]
Somewhy my project doesn't see the Coinbase facade. 
```bash
php artisan cache:clear
composer dump-autoload
```
didn't help

**Comment by duynguyenhoang** [comment]
Add `use Coinbase;` should help you

**Comment by antimech** [comment]
Could you please provide more details and steps to reproduce?

**Comment by antimech** [comment]
Closed due inactivity.

**Comment by BNhashem16** [comment]
the same problem, with me!

**Comment by antimech** [comment]
@BNhashem16 have you imported the facade `Shakurov\Coinbase\Facades\Coinbase`?
