### ISSUE TITLE
Variable payment always shows donation when completed?

### ISSUE THREAD

**Issue by ghost** [shakurov/laravel-coinbase#7]
I am developing a website with wallet feature. User can add any amount to their wallet, which can be used to play games or buy stuffs on the website. The site accepts cryptocurrency as their main payment.

ISSUE:
I have used shakurov/laravel-coinbase to accept the cryptocurrency payment. I am creating charges using "no_price" as pricing type. And when user pays using cryptocurrency, the completed screen shows "Thank you for your donation". I cannot find how to update this text creating charges.
Please help!!

**Comment by antimech** [comment]
Currently the API doesn't allow to overwrite the behavior. Please refer your future questions to the Coinbase Commerce support: support@coinbase.com
